e2e/cardNews.spec.ts, src/App.tsx, src/components/home/__tests__/cardNewsComponent.test.tsx, src/components/home/cardNewsComponent.tsx
홈 학생 소식 카드 뉴스 컴포넌트 개발
1. 학생 소식 카드 뉴스 컴포넌트 작성
2. 테스트 코드 작성
- 렌더링 및 text-overflow
=> 🌟 feat : 홈 학생 소식 카드 뉴스 컴포넌트 개발

e2e/homeCategoryButton.spec.ts, src/App.tsx, src/components/home/__tests__/homeCategoryButton.test.tsx, src/components/home/homeCategoryButton.tsx
홈 카테고리 버튼 추가
1. 카테고리 버튼 작업
2. 이모지 및 텍스트 입력 가능
3. 테스트 코드 작성
=> 🌟 feat : 홈 카테고리 버튼 추가

e2e/chatBar.spec.ts, src/components/Toast/Toast.tsx, src/components/chat/ChatBar.tsx, src/main.tsx, src/pages/Devtools/index.tsx, src/styles/ChatBarStyles.tsx, src/styles/TopBarStyles.tsx
Close MM-130
- 메시지 입력 및 전송을 위한 ChatBar 컴포넌트 구현
- 이모티콘, 첨부파일 추가 버튼 UI 및 이벤트 핸들러 구현
- 하단 sticky 포지션으로 화면 고정 레이아웃 적용
- 상단 sticky 포지션으로 Topbar 고정
- 페이지별로 ChatBar 표시 여부 조정 필요
- 추후 실제 이모티콘 선택 UI 연동 필요
- 아이콘 접근성 개선 필요
=> 🌟 feat: 메시지 입력을 위한 ChatBar 컴포넌트 추가

e2e/detailReview.spec.ts, src/components/review/DetailReview.tsx, src/pages/Devtools/index.tsx, src/styles/DetailReviewStyles.tsx
Close MM-120
- 사용자 리뷰를 효과적으로 표시하는 DetailReview 컴포넌트 구현
- 상세 리뷰 제목과 전체보기 버튼이 포함된 헤더 섹션 구현
=> ✨ feat: 상세 리뷰 컴포넌트 구현

e2e/detailReview.spec.ts, e2e/star.spec.ts, src/components/review/DetailReview.tsx, src/components/review/Star.tsx, src/pages/Devtools/index.tsx, src/styles/DetailReviewStyles.tsx, src/styles/StarStyles.tsx
Close MM-123
- 5개의 별로 구성된 별점 컴포넌트 구현
- 읽기 전용 모드와 인터랙티브 모드 지원
- 외부 상태 관리를 위한 onChange 콜백 함수 제공
=> ⭐ feat: 재사용 가능한 Star 별점 컴포넌트 구현

e2e/chatTest.spec.ts, src/components/chat/ChatBar.tsx, src/components/emoticon/EmoticonPicker.tsx, src/pages/ChatTest/ChatTest.tsx, src/pages/ChatTest/index.tsx, src/pages/Devtools/index.tsx, src/routes/index.tsx, src/styles/ChatBarStyles.tsx, src/styles/EmoticonPickerStyles.tsx
Close MM-132
- 반응형 디자인 적용
- 이모티콘 선택 및 채팅 인터페이스 통합
- 이모티콘 그리드 레이아웃의 반응형 구현
- 채팅 기능 및 이모티콘 전송 기능에 대한 테스트 코드 구현
- CharBar.tsx
- ChatBarStyles.tsx
=> 🌟 feat : 이모티콘 리스트 컴포넌트 구현

src/components/buttons/filterButton.tsx, src/components/chat/ChatBar.tsx, src/components/chat/pageComponent/ChatItem.tsx, src/components/chat/pageComponent/styles/ChatItemStyles.tsx, src/components/customForm/AnswerInput.tsx, src/components/customForm/AskInput.tsx, src/components/icon/iconComponents.tsx, src/components/navigation/navigationComponent.tsx, src/pages/Chat/ChatHome.tsx, src/pages/Chat/ChatRoom.tsx, src/pages/Chat/CustomFormMake.tsx, src/pages/Chat/CustomFormView.tsx, src/pages/Chat/styles/ChatHomeStyles.tsx, src/pages/Chat/styles/ChatRoomStyles.tsx, src/pages/Chat/styles/CustomFormMakeStyles.tsx, src/pages/Chat/styles/CustomFormViewStyles.tsx, src/pages/Chat/styles/rootStyles.tsx, src/pages/Matching/style.tsx, src/routes/index.tsx, src/styles/TopBarStyles.tsx, yarn.lock
- navigation, Topbar 반응형 추가
- 채팅홈 구현
- 채팅 기능 추가
- 커스텀폼 페이지 추가
- 라우팅
- 바텀시트 적용
- 밀린 반응형 모두 적용
- 백엔드 연결
=> 🌟 feat : 채팅 구현

src/styles/OnboardingStyles.tsx
develop/MM-30
- 모바일화면에서 적합한 화면 구성을 위해 header의 높이 조정
- 로그인 버튼의 하단 마진 조정
=> 🎨 style: 모바일을 위한 온보딩 스타일 수정

src/index.css, src/pages/Onboarding/Onboarding.tsx, src/pages/Register/style.tsx, src/styles/OnboardingStyles.tsx, vite.config.ts
=> 😎 fix : 온보딩 버그 수정

src/pages/Chat/ChatRoom.tsx, src/pages/Emoticons/style.tsx, src/pages/Onboarding/Auth.tsx
1. fetchMessages 함수 개선
- 메시지 병합: 기존 메시지 + 새 메시지 중복 제거
- 선택적 로딩 표시: 초기 로드시에만 스피너 표시
- 재시도 횟수 증가: 3회 → 8회
2. 에러 처리 강화
- JSON 파싱 전 응답 타입 검증
- 인증 오류 시 재시도 중단
- 최대 재시도 후에도 에러 UI 표시 안함
3. UI 개선
- 에러 메시지 및 재시도 버튼 제거
- 메시지가 없을 때만 안내 메시지 표시
4. 코인 구매 및 사용 내역 UI 개선
-  탑바와 컨테이서 사이 간격 조정
=> 🎨 style : 연결 오류시에도 채팅 화면이 일관되도록 수정

src/components/modal/modalComponent.tsx, src/pages/Chat/ChatRoom.tsx, src/pages/Matching/application.tsx, src/pages/Onboarding/Auth.tsx
매칭이 성사되면 자동으로 해당 채팅방으로 이동
- 매칭 수락 API 응답으로 받은 채팅방 ID를 이용한 자동 이동
- 채팅방 이동 시 상대방 정보 정확한 전달
- 채팅방에서 상대방 이름이 "상대방"이 아닌 실제 닉네임으로 표시
- 채팅방 상태에 따른 BottomSheet 메뉴 개선
=> 😎fix: 매칭 수락 시 채팅방 자동 이동 기능 구현

src/components/modal/modalComponent.tsx, src/pages/Matching/application.tsx, src/pages/Onboarding/Auth.tsx
- 매칭 신청 정보 페이지에 삭제 버튼 추가
- 매칭방 삭제 확인 모달 구현
- PATCH /matchings/{matchingId} API 연동
- 삭제 성공 시 매칭방 목록으로 이동
=> 🌟feat:매칭방 삭제 기능 추가

src/App.tsx, src/components/coin/CoinPurchase.tsx, src/components/coin/EventCoinPurchase.tsx, src/components/home/StudentSupportLink.tsx, src/components/modal/modalComponent.tsx, src/pages/Emoticons/emoticonHome.tsx, src/pages/Emoticons/emotionPurchase.tsx, src/pages/Emoticons/pointPurchase.tsx, src/pages/Emoticons/purchaseFail.tsx, src/pages/Emoticons/purchaseSuccess.tsx, src/pages/Home/Home.tsx, src/pages/Onboarding/Auth.tsx, src/routes/index.tsx, src/services/api.ts, src/utils/fetchWithRefresh.ts, yarn.lock
- 이모티콘 구매 기능 추가
- 코인 구매 기능 추가
- 결제 위젯 버그 수정
=> 이모티콘 구매 및 코인 구매 기능 추가

.gitignore, src/components/chat/ChatBar.tsx, src/components/toast/ToastProvider.tsx, src/hooks/useChatRoom.ts, src/hooks/useCustomForm.ts, src/hooks/useMessageProcessor.ts, src/main.tsx, src/pages/Chat/ChatHome.tsx, src/pages/Chat/ChatRoom.tsx, src/pages/Chat/CustomFormMake.tsx, src/pages/Chat/CustomFormView.tsx, src/pages/Magazine/MagazineWrite.tsx, src/pages/Magazine/styles/EmoticonButtonStyles.tsx, src/styles/ChatBarStyles.tsx, src/types/message.ts
- 채팅 메시지 비속어 필터링 기능 추가
- 채팅 정보 토스트박스 시스템 구현
- 커스텀폼 소유권 및 실시간성  개선
- ChatBar 다중라인 입력 지원
- ChatRoom 컴포넌트 리팩토링
- info 토스트박스의 유지 시간 연장
├── useChatRoom.ts        ← 채팅방 전체 관리
├── useCustomForm.ts      ← 커스텀폼 전용 로직
├── useMessageProcessor.ts ← 메시지 처리 로직
└── useSocketMessage.ts   ← 웹소켓 연결 관리
1. useChatRoom.ts - 메인 채팅방 관리
역할: 채팅방의 전반적인 상태와 동작 관리
- 메시지 목록 상태 관리
- 웹소켓 구독 관리
- 읽음 처리
- 메시지 전송
- 이모티콘 전송
- 에러 처리
2. useCustomForm.ts - 커스텀폼 전용 로직
역할: 커스텀폼 관련 모든 로직 독립 관리
- 커스텀폼 메시지 처리
- 폼 데이터 조회
- 답변 완료 시 메시지 제거
- 커스텀폼 상태 관리
- API 호출 관리
3. useMessageProcessor.ts - 메시지 처리 로직
역할: 메시지 파싱 및 처리 전담
- 메시지 타입별 파싱
- 메시지 추가/정렬
- 텍스트 메시지 처리
- 시스템 메시지 처리
- 중복 메시지 방지
4. useSocketMessage.ts - 웹소켓 연결 관리 (기존)
역할: 전역 웹소켓 연결 상태 관리
- 웹소켓 연결/해제
- 읽지 않은 메시지 수 관리
- 전역 구독 관리
=> 😎fix: 채팅 시스템 개선 및 커스텀폼 실시간성 강화

nginx.conf, src/components/inputs/yellowInputBox.tsx, src/pages/Chat/ChatHome.tsx, src/pages/Home/NotificationItem.tsx, src/pages/Home/NotificationPage.tsx, src/pages/Home/NotificationStyles.tsx, src/pages/Matching/registerChatRoom.tsx, src/pages/Onboarding/Auth.tsx
알림페이지에 API를 연결하여 알림이 보이도록 수정하였습니다 : )
=> 🎉 update : 알림페이지 백엔드 연결

nginx.conf, src/components/inputs/yellowInputBox.tsx, src/pages/Chat/ChatHome.tsx, src/pages/Matching/registerChatRoom.tsx
매칭방 생성 시 글자 길이 검증 및 토스트박스 알람 설정
=> 😎 fix : 최대 글자길이 검증 로직 추가

src/hooks/useChatRoom.ts, src/pages/Chat/ChatRoom.tsx
- 리팩토링 과정에서 몇 기능들이 누락돼 다시 복원해뒀습니다! 
- 다시 천천히 수정해보겠습니다..
=> 🎉update: 리팩토링 실패.. 복원

src/pages/Chat/ChatRoom.tsx, src/pages/Matching/matchedInfo.tsx, src/pages/Onboarding/Auth.tsx
=> 😎fix: 리뷰페이지 라우팅 오류 해결

src/hooks/useChatRoom.ts, src/pages/Chat/ChatRoom.tsx, src/pages/Matching/index.tsx, src/pages/Mypage/DetailReviewPage.tsx
- 채팅방 프로필 이미지 오류 해결 : 예전에 messages API에 프로필 이미지 안 줬을때 버전이 남아있어서 업데이트 했습니다!
- 전체 리뷰 페이지 수정 : 상대방 리뷰가 보이는 문제를 해결하고자 내 프로필 조회 후 id를 사용하도록 수정했습니다!
=> 😎 fix : 채팅방 프로필 이미지 오류 & 전체 리뷰 오류 수정

src/pages/Emoticons/emoticonHome.tsx, src/pages/Emoticons/emotionPurchase.tsx
- 이모티콘 구매 후 topbar에서 back 버튼을 누르면 /fail 페이지로 넘어가는 오류 수정
- 이모티콘 구매 api 중복 호출 검증
=> 😎fix: 이모티콘 구매 api 중복 호출 검증

src/pages/Home/Home.tsx, src/pages/Matching/index.tsx
- 매칭 2개씩 나오는 문제를 키를 고유하게 관리하는 형태로 수정했습니다!
- 홈화면에 추천 이모티콘을 4개만 보이도록 수정했습니다!
=> 😎 fix : 매칭 2개씩 나오는 문제 해결 - 키 고유하게 관리

src/pages/Emoticons/pointPurchase.tsx
😎 fix : 구매 가능한 상품 API 호출 오류 수정
=> 😎 fix : 구매 가능한 상품 API 호출 오류 수정

src/pages/Chat/ChatRoom.tsx, src/pages/Matching/application.tsx, src/pages/Mypage/Mypage.tsx, src/pages/Onboarding/Onboarding.tsx, src/utils/fetchWithRefresh.ts
=> 😎 fix : 로그인 오류 및 프로필 조회 오류 수정

src/components/chat/ChatBar.tsx, src/pages/Chat/ChatRoom.tsx
=> 🎉update: pwa 키보드 수정

src/pages/Matching/index.tsx
=> 🎉 update : 무한 스크롤 추가
